type: object
description: |
  In game item object, it represents the Sword, Pistol, LMG.. what ever the user
  is able to hold in his inventory. See ItemProperty for property decorations
properties:
  id: integer
  title: string
  description: string
  image_url: string
  related_items: RelatedItem[]
  item_properties: ItemProperty[]
