type: object
description: |
  Item Properties represents the meat on an item, you can add as much properties
  as you want. So for a Pistol it could be "Magazine Size", "20"... a Sword could
  have a "Length", "1m"
properties:
  name: string
  value: string
  public: boolean
